In [4]:

# NumPy Arrays & Matrix Operations


import numpy as np


# Creating different arrays

arr1 = np.array([5, 10, 15, 20, 25])

arr2 = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

arr3 = np.array([
    [[1, 2], [3, 4]],
    [[5, 6], [7, 8]]
])

print("1D Array")
print(arr1)

print("\n2D Array")
print(arr2)

print("\n3D Array")
print(arr3)

# keywords to use to find out the shape, dimensions, size and datatype of the array

print("Shape :", arr3.shape)
print("Dimensions :", arr3.ndim)
print("Size :", arr3.size)
print("Datatype :", arr3.dtype)

1D Array
[ 5 10 15 20 25]

2D Array
[[1 2 3]
 [4 5 6]]

3D Array
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
Shape : (2, 2, 2)
Dimensions : 3
Size : 8
Datatype : int64


In [ ]:
# Basic arrays that are used in operations 

zeros = np.zeros((3, 3))
ones = np.ones((2, 4))
identity = np.eye(3)

random = np.random.randint(1, 50, (3, 3))

print("Zeros Matrix")
print(zeros)

print("\nOnes Matrix")
print(ones)

print("\nIdentity Matrix")
print(identity)

print("\nRandom Matrix") # used to generate random numbers in arrays 
print(random)

Zeros Matrix
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]

Ones Matrix
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]

Identity Matrix
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

Random Matrix
[[41  6 36]
 [30 11  1]
 [46 25 31]]


In [ ]:
# Matrix operations

A = np.array([
    [2, 4],
    [6, 8]
])

B = np.array([
    [1, 3],
    [5, 7]
])

print("Matrix A")
print(A)

print("\nMatrix B")
print(B)

# Addition

add = A + B

print("Result")
print(add)


# Subtraction

sub = A - B

print(sub)

# Element-wise multiplication

mul = A * B

print(mul)

# Matrix multiplication

product = A @ B

print(product)

# Transpose

print("Transpose of A")
print(A.T)

# Determinant

det = np.linalg.det(A)

print("Determinant =", det)

# Inverse

inv = np.linalg.inv(A)

print(inv)

# Eigenvalues and Eigenvectors

values, vectors = np.linalg.eig(A)

print("Eigenvalues")
print(values)

print("\nEigenvectors")
print(vectors)

# Statistics

print("Maximum =", A.max())
print("Minimum =", A.min())
print("Mean =", A.mean())
print("Sum =", A.sum())
print("Standard Deviation =", A.std())
# Creating sequence and reshaping

nums = np.arange(1, 13)

print("Original Array")
print(nums)

nums = nums.reshape(3, 4)

print("\nReshaped Array")
print(nums)
# Indexing and slicing

data = np.array([
    [11, 22, 33],
    [44, 55, 66],
    [77, 88, 99]
])

print(data)

print("\nFirst Row")
print(data[0])

print("\nSecond Column")
print(data[:, 1])

print("\nLast Two Rows")
print(data[1:, :])

print("\nBottom Right Part")
print(data[1:, 1:])

# Broadcasting

marks = np.array([
    [70, 75, 80],
    [85, 90, 95]
])

bonus = np.array([2, 2, 2])

updated = marks + bonus

print(updated)

# Student marks example

marks = np.array([
    [85, 78, 91],
    [76, 88, 80],
    [92, 90, 89],
    [68, 74, 81]
])

print("Marks")
print(marks)

print("\nAverage of each student")
print(np.mean(marks, axis=1))

print("\nAverage of each subject")
print(np.mean(marks, axis=0))

print("\nHighest marks in every subject")
print(np.max(marks, axis=0))

print("\nLowest marks in every subject")
print(np.min(marks, axis=0))


# Finding maximum and minimum values

print("Highest mark:", marks.max())
print("Lowest mark:", marks.min())

# Flattening

flat = marks.flatten()

print(flat)

# Vertical stacking

x = np.array([[1, 2], [3, 4]])
y = np.array([[5, 6], [7, 8]])

print(np.vstack((x, y)))

# Horizontal stacking

print(np.hstack((x, y)))

# Splitting arrays

arr = np.arange(12)

parts = np.split(arr, 3)

print(parts)

# Boolean indexing

nums = np.array([12, 25, 8, 31, 45, 10])

print("Numbers greater than 20")
print(nums[nums > 20])

# Solving linear equations

coef = np.array([
    [3, 2],
    [1, 2]
])

ans = np.array([18, 14])

sol = np.linalg.solve(coef, ans)

print("Solution")
print(sol)

# Random numbers

random_values = np.random.rand(4, 4)

print(random_values)

# Copy vs View

a = np.array([10, 20, 30, 40])

b = a.copy()
c = a.view()

a[0] = 100

print("Original")
print(a)

print("Copy")
print(b)

print("View")
print(c)

# Simple practical example

sales = np.array([
    [1200, 1500, 1700],
    [1000, 1100, 1400],
    [1800, 1600, 1900]
])

print("Sales Data")
print(sales)

print("\nTotal Sales")
print(sales.sum())

print("\nAverage Sales")
print(sales.mean())

print("\nHighest Sale")
print(sales.max())

print("\nSales by Month")
print(sales.sum(axis=0))